import React from 'react'

const Page = () => {
  return (
    <div className='min-h-[100vh] bg-[#F6F6F8] py-[10px]'>
      <div className='container'>
        <div className='pb-[23px]'>
          <h1 className='text-center uppercase font-[600]!'>Privacy Policy</h1>
          <span className='w-[100%] my-[15px] mx-auto block max-w-[145px] md:max-w-[235px] h-[1px] bg-[#24C16F]' />
        </div>
        <div className="text-[14px] leading-[22px]">
          <p className='mb-[24px]' >We hold in high esteem the privacy of every Innocode's user. This Privacy Policy contains the details about the information Innocode will collect and how we will make use of the said information in terms of Information Technology Act 2000 and rules thereunder. Innocode wants you to make a note of when and how personal information is collected, used, disclosed and protected.</p>
          <p className='mb-[24px]' >Most importantly, you agree and consent to the fact that Innocode may collect, use and disclose your Personal Information in accordance with this Policy. If you do not agree with these terms, you are requested not to provide any personal information to us.</p>
          <p className='mb-[24px]' ><strong>1. Personal information we collect:</strong><br />Innocode collects and processes personal information when you register at Innocode platform or otherwise use our services, which information includes your name, email, mobile, address and other details i.e. the information that you provide us at the time of signup with Innocode. And other information that you may enter during the use of the services, that may remain stored in our database and form part of your profile or otherwise.</p>
          <p className='mb-[24px]' >Further, Innocode also collects other basic information by your use of our services. When you visit the Site, we automatically collect certain information about your device, including information about your web browser, IP address, time zone, and some of the cookies that are installed on your device. Additionally, as you browse the Site, we collect information about the individual web pages or products that you view, what websites or search terms referred you to the Site, and information about how you interact with the Site. We refer to this automatically-collected information as "Device Information".<br />We collect Device Information using the following technologies:<br />● "Cookies" are data files that are placed on your device or computer and often include an anonymous unique identifier. <br />● "Log files" track actions occurring on the Site, and collect data including your IP address, browser type, Internet service provider, referring/exit pages, and date/time stamps. <br />● "Web beacons", "tags", and "pixels" are electronic files used to record information about how you browse the Site. <br />● We store cookies, Google Ads conversion tracking and Facebook Pixel. <br />Additionally, when you make a purchase or attempt to make a purchase through the Site, we collect certain information from you, namely Order Information. When we talk about "Personal Information" in this Privacy Policy, we are talking both about Device Information and Order Information.</p>
          <p className='mb-[24px]' ><strong>2. How do we use your information:</strong><br />As you will see in the Policy, we only use the information collected to improve our services for our users. <br />Personal Information:</p>
          <p className='mb-[24px]' >Innocode uses the personal information (other than sensitive information) for fulfilling your needs and requests for products and services, improving user experience, sending transactional emails or notification you have opted for, for displaying relevant advertisements according to your location, products/services rendered, etc. <br />Device Information: We use the Device Information that we collect to help us screen for potential risk and fraud (in particular, your IP address), and more generally to improve and optimize our Site (for example, by generating analytics about how our customers browse and interact with the Site, and to assess the success of our marketing and advertising campaigns). <br />Further, the device information may be required to be disclosed in circumstances as provided herein below, mainly when required to be disclosed by some government or enforcement agency. <br />Do not track: Please note that we do not alter our Site's data collection and use practices when we see a Do Not Track signal from your browser. <br />Order Information: We use the Order Information that we collect generally to fulfill any orders placed through the Site (including processing your payment information, arranging for shipping, and providing you with invoices and/or order confirmations). Additionally, we use this Order Information to:<br />● Communicate with you;<br />● Screen our orders for potential risk or fraud; and<br />● When in line with the preferences you have shared with us, provide you with information or advertising relating to our products or services. <br />Sensitive Information:</p>
          <p className='mb-[24px]' >Further, Innocode collects and treats the sensitive information in terms of Information Technology Act, 2000 read with the rules thereunder, as under:</p>
          <p className='mb-[24px]' >&nbsp; &nbsp; (i) Login Password: The registration requires you to create a password for accessing Innocode services, which is confidential and sensitive information, collected and retained within the Innocode database in encrypted format. But the said sensitive information is just used by you as a Innocode user for gaining access to the services and is not used or otherwise can be accessed by Innocode or its affiliates / partners in any way.</p>
          <p className='mb-[24px]' >&nbsp; &nbsp; (ii) Financial Information: In case of payment made by a secured Payment Gateway at Innocode, the information is processed at the Payment Gateway, who are PCI Compliant and do not retain the sensitive information for the period more than required. The said online payments are additionally subject to an independent agreement with the payment gateway provider.</p>
          <p className='mb-[24px]' >Otherwise, the Bank Details may be visible on the cheques couriered to us for payment of any services, but the complete bank account details are never noted down or processed for any reasons whatsoever at Innocode. Though we recommend direct deposit of payments in our Bank Account either electronic transfer or by drop of cheque.</p>
          <p className='mb-[24px]' ><strong>4. Sharing you personal Information:</strong><br />Innocode do not rent, sell, or share personal information (other than sensitive information) about you with any third parties, except when we have specifically obtained your consent at the time of collection of the information online at Innocode or otherwise offline, and / or to provide products or services you've requested, or under the following circumstances:</p>
          <p className='mb-[24px]' >&nbsp; &nbsp; 1. We provide the information, other than sensitive information to trusted partners who work on our behalf or with us under confidentiality agreements for the purpose of creating / modifying / maintaining the Services. However, these companies do not have any independent right to share / use this information for any other purpose, except for that specifically authorised by us.</p>
          <p className='mb-[24px]' >&nbsp; &nbsp; &nbsp; &nbsp;2. Innocode's administrator may be required to login to the admin panel for troubleshooting, as a result can get access to the personal data, but which purely can only be for administration and troubleshooting purposes.</p>
          <p className='mb-[24px]' >&nbsp; &nbsp; &nbsp; &nbsp;3. Innocode believe it is necessary to share information in order to investigate, prevent, or take action regarding illegal activities, suspected fraud, situations involving potential threats to the physical safety of any person, violations of User Agreement, or as otherwise required by law;</p>
          <p className='mb-[24px]' >&nbsp; &nbsp; &nbsp; &nbsp;4. Innocode may also share your Personal Information to comply with applicable laws and regulations, to respond to court orders, subpoena, search warrant or other lawful request for information we receive, or to establish or exercise our legal rights or defend against legal claims;</p>
          <p className='mb-[24px]' >&nbsp; &nbsp; &nbsp; &nbsp;5. Innocode transfers information about you if our software is acquired by or merged with another company. In this event, we will notify you before information about you are transferred and becomes subject to a different privacy policy;</p>
          <p className='mb-[24px]' >&nbsp; &nbsp; &nbsp; &nbsp;6. Innocode also uses Google Analytics to help us understand how our customers use the Site — you can read more about how Google uses your Personal Information here: https://www.google.com/intl/en/policies/privacy/. you can also opt-out of Google Analytics here: https://tools.google.com/dlpage/gaoptout.</p>
          <p className='mb-[24px]' >Innocode never uses or shares the personally identifiable information provided to us online in ways or for reasons unrelated to the ones described above. The User shall be deemed to have consented to disclosure of Personal Information (other than sensitive information) by Innocode to its affiliates and business partners by providing such Personal information to Innocode in the course of Innocode's performance of the Services.</p>
          <p className='mb-[24px]' ><strong>5. Advertisement &amp; Newsletter:</strong><br />Innocode reserves the right to send you certain communications relating to our services or sponsored advertisements, administrative messages and the Newsletter, that are considered part of your registered account, with an option for you to stop receiving them. We shall also send you emails which shall contain information about our existing or new services or features. For the purpose, we use your Personal Information to provide you with relevant information.</p>
          <p className='mb-[24px]' ><strong>6. Security Practices:</strong></p>
          <p className='mb-[24px]' >Personal information, including sensitive information about users that is maintained on Innocode systems and is protected using industry standard security measures. We maintain a variety of physical, electronic, and procedural safeguards to guard your personal information. You should be aware that Innocode has no control over the security of other sites on the Internet you might visit, interact with, or from which you buy products or services. You should keep your user name, password or other access information safe and confidential to protect against unauthorized access to your account information and services.</p>
          <p className='mb-[24px]' >You acknowledge that, notwithstanding the security features of the Services, no product, hardware, software or service can provide a completely secure mechanism of electronic transmission or communication and that there are persons and entities, including enterprises, governments and quasi-governmental actors, as well as technologies, that may attempt to breach any electronic security measure. Innocode will not be liable to you for any disclosures of Users Materials to third parties or any other breaches of security affecting you or User Materials.</p>
          <p className='mb-[24px]' ><strong>7. How long Information is retained:</strong></p>
          <p className='mb-[24px]' >We may require additional information from you to allow us to confirm your identity. Further, if we are processing your information on behalf of one of our clients, we will refer you to that client, and will support them to the extent required by applicable law in responding to your request. Please note that we store information as necessary to fulfil the purposes for which it was collected, and may continue to retain and use the information even after a data subject request for purposes of our legitimate interests, including as necessary to comply with our legal obligations, resolve disputes, prevent fraud, and enforce our agreements.<br />The Credit Card Information is collected by the Payment Gateway for processing of payment and deleted soon thereafter, as declared above. Otherwise, no outside agency has been authorized for the use of any sensitive information till now but as and when any such authorization is made in the near future, the details would be posted here as to the same.</p>
          <p className='mb-[24px]' >Additionally, you may also request that Innocode may delete your Personal Information from the system and records. Additionally, you may request to delete/remove your account anytime at your own free, if you are covered under GDPR policy. However, due to technical constraints and the fact that we backup our systems at regular intervals. Personal Information may continue to reside in our backup systems after deletion for some limited time.</p>
          <p className='mb-[24px]' ><strong>8. GDPR Policy:</strong></p>
          <p className='mb-[24px]' >Innocode serves as a data processor under the GDPR, and adheres to the principles and rules of the GDPR. Specifically, Innocode implements privacy by design and default principles, ensures limited data retention protocols, adheres to incident response norms, allows for appropriate third party audits, ensures data is only transferred internationally with a lawful basis, only contracts with sub processors with adequate written commitments to data processing, respects data subject rights, does not process sensitive personal data, and provides data processing agreements to all appropriate clients and partners.</p>
          <p className='mb-[24px]' >If you are a data subject in Europe, you have the right to access, rectify, or erase any personal data we have collected about you through the Services. You also have the right to data portability and the right to restrict or object to our processing of personal data we have collected about you through the Services. You have the right to ask that your personal information be corrected, updated, or deleted. <br />In addition, you have the right to ask us not to process your personal data (or provide it to third parties to process) for marketing purposes or purposes materially different than for which it was originally collected or subsequently authorized by you. You may withdraw your consent at any time for any data processing we do based on consent you have provided to us.<br />If you would like to exercise this right, contact us at legal@innocode.in and specify which right you intend to exercise. We will respond to your request within 30 (thirty) days.</p>
          <p className='mb-[24px]' ><strong>9. Data Retention:</strong><br />Innocode holding sensitive/ personal data or information of providers of information, shall not retain such information for longer than is required for the purposes for which the information may lawfully be used or is otherwise required under the User Agreement or any other law for the time being in force or unless ordered to the contrary by any order of court of law. The information collected shall be used for the purpose for which it has been collected.</p>
          <p className='mb-[24px]' >Specifically, in case of payment made by a secured Payment Gateway at our website, the information is processed at the Payment Gateway, who are PCI Compliant and do not retain the sensitive information for the period more than required. The said online payments are additionally subject to an independent agreement with the payment gateway provider.</p>
          <p className='mb-[24px]' ><strong>10. Data Storage:</strong></p>
          <p className='mb-[24px]' >The personal information is collected and retained by Innocode and EnDetect Software on it's server located in Germany, in case of accounts registered with us.</p>
          <p className='mb-[24px]' >In the case of software services, data is collected and stored on our servers, only in case you opt for the EnDetect Free and EnDetect Lite version of Software only. Else, if you buy EnDetect Pro edition we store all data on your premise or on your cloud except license information on our server for verification purposes.</p>
          <p className='mb-[24px]' ><strong>11. Changes:</strong><br />We may update this policy from time to time. We may notify you about significant changes in the way we treat personal information by sending a notice to the primary email address specified in your registered account or by placing a notice on our site for a reasonable period of time.</p>
          <p className='mb-[24px]' ><strong>12. Questions About This Privacy Policy:</strong></p>
          <p className='mb-[24px]' >If you have an unresolved privacy or data use concern that a Innocode client or Innocode has not addressed satisfactorily, please contact legal@innocode.in.</p>
          <p className='mb-[24px]' >Contact Information<br />If you have any questions regarding this Privacy Policy or would like more information on our privacy practices, please contact us at legal@innocode.in or by mail at:</p>
          <p className='mb-[24px]' ><strong>Vijay Paudyal</strong><br /><strong>[Re: Privacy Compliance Officer]</strong><br /><strong>Innocode Ventures, F-101, </strong><br /><strong>Bali Nagar, New Delhi – 110015 India</strong></p>
        </div>
      </div>
    </div>
  )
}

export default Page